<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/ownmfa_app_identity.proto

namespace Ownmfa\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * BackupsCodesMethod configures a backup codes method. Identities using this method are immediately activated and do not require activation.
 *
 * Generated from protobuf message <code>ownmfa.api.BackupsCodesMethod</code>
 */
class BackupsCodesMethod extends \Google\Protobuf\Internal\Message
{
    /**
     * Number of passcodes provided.
     *
     * Generated from protobuf field <code>int32 passcodes = 1 [(.validate.rules) = {</code>
     */
    protected $passcodes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $passcodes
     *           Number of passcodes provided.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\OwnmfaAppIdentity::initOnce();
        parent::__construct($data);
    }

    /**
     * Number of passcodes provided.
     *
     * Generated from protobuf field <code>int32 passcodes = 1 [(.validate.rules) = {</code>
     * @return int
     */
    public function getPasscodes()
    {
        return $this->passcodes;
    }

    /**
     * Number of passcodes provided.
     *
     * Generated from protobuf field <code>int32 passcodes = 1 [(.validate.rules) = {</code>
     * @param int $var
     * @return $this
     */
    public function setPasscodes($var)
    {
        GPBUtil::checkInt32($var);
        $this->passcodes = $var;

        return $this;
    }

}

