<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/ownmfa_user.proto

namespace Ownmfa\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * CreateUserRequest is sent to create a user.
 *
 * Generated from protobuf message <code>ownmfa.api.CreateUserRequest</code>
 */
class CreateUserRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * User message to create.
     *
     * Generated from protobuf field <code>.ownmfa.api.User user = 1 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     */
    protected $user = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ownmfa\Api\User $user
     *           User message to create.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\OwnmfaUser::initOnce();
        parent::__construct($data);
    }

    /**
     * User message to create.
     *
     * Generated from protobuf field <code>.ownmfa.api.User user = 1 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     * @return \Ownmfa\Api\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * User message to create.
     *
     * Generated from protobuf field <code>.ownmfa.api.User user = 1 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     * @param \Ownmfa\Api\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Ownmfa\Api\User::class);
        $this->user = $var;

        return $this;
    }

}

