<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/ownmfa_org.proto

namespace Ownmfa\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * CreateOrgRequest is sent to create an organization.
 *
 * Generated from protobuf message <code>ownmfa.api.CreateOrgRequest</code>
 */
class CreateOrgRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Org message to create.
     *
     * Generated from protobuf field <code>.ownmfa.api.Org org = 1 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     */
    protected $org = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ownmfa\Api\Org $org
     *           Org message to create.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\OwnmfaOrg::initOnce();
        parent::__construct($data);
    }

    /**
     * Org message to create.
     *
     * Generated from protobuf field <code>.ownmfa.api.Org org = 1 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     * @return \Ownmfa\Api\Org|null
     */
    public function getOrg()
    {
        return $this->org;
    }

    public function hasOrg()
    {
        return isset($this->org);
    }

    public function clearOrg()
    {
        unset($this->org);
    }

    /**
     * Org message to create.
     *
     * Generated from protobuf field <code>.ownmfa.api.Org org = 1 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     * @param \Ownmfa\Api\Org $var
     * @return $this
     */
    public function setOrg($var)
    {
        GPBUtil::checkMessage($var, \Ownmfa\Api\Org::class);
        $this->org = $var;

        return $this;
    }

}

