<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/ownmfa_session.proto

namespace Ownmfa\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * CreateKeyRequest is sent to create an API key.
 *
 * Generated from protobuf message <code>ownmfa.api.CreateKeyRequest</code>
 */
class CreateKeyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Key message to create.
     *
     * Generated from protobuf field <code>.ownmfa.api.Key key = 1 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     */
    protected $key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ownmfa\Api\Key $key
     *           Key message to create.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\OwnmfaSession::initOnce();
        parent::__construct($data);
    }

    /**
     * Key message to create.
     *
     * Generated from protobuf field <code>.ownmfa.api.Key key = 1 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     * @return \Ownmfa\Api\Key|null
     */
    public function getKey()
    {
        return $this->key;
    }

    public function hasKey()
    {
        return isset($this->key);
    }

    public function clearKey()
    {
        unset($this->key);
    }

    /**
     * Key message to create.
     *
     * Generated from protobuf field <code>.ownmfa.api.Key key = 1 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     * @param \Ownmfa\Api\Key $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkMessage($var, \Ownmfa\Api\Key::class);
        $this->key = $var;

        return $this;
    }

}

