<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/ownmfa_app_identity.proto

namespace Ownmfa\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * HardwareTOTPMethod configures a hardware OATH TOTP one-time password method.
 *
 * Generated from protobuf message <code>ownmfa.api.HardwareTOTPMethod</code>
 */
class HardwareTOTPMethod extends \Google\Protobuf\Internal\Message
{
    /**
     * Hardware TOTP hash function. Defaults to SHA512 if not specified.
     *
     * Generated from protobuf field <code>.ownmfa.api.Hash hash = 1;</code>
     */
    protected $hash = 0;
    /**
     * Passcode digits length.
     *
     * Generated from protobuf field <code>int32 digits = 2 [(.validate.rules) = {</code>
     */
    protected $digits = 0;
    /**
     * Hardware TOTP secret. Only included during identity creation. When used in JSON, the value will be represented as a base64 string.
     *
     * Generated from protobuf field <code>bytes secret = 3 [(.validate.rules) = {</code>
     */
    protected $secret = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $hash
     *           Hardware TOTP hash function. Defaults to SHA512 if not specified.
     *     @type int $digits
     *           Passcode digits length.
     *     @type string $secret
     *           Hardware TOTP secret. Only included during identity creation. When used in JSON, the value will be represented as a base64 string.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\OwnmfaAppIdentity::initOnce();
        parent::__construct($data);
    }

    /**
     * Hardware TOTP hash function. Defaults to SHA512 if not specified.
     *
     * Generated from protobuf field <code>.ownmfa.api.Hash hash = 1;</code>
     * @return int
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Hardware TOTP hash function. Defaults to SHA512 if not specified.
     *
     * Generated from protobuf field <code>.ownmfa.api.Hash hash = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkEnum($var, \Ownmfa\Api\Hash::class);
        $this->hash = $var;

        return $this;
    }

    /**
     * Passcode digits length.
     *
     * Generated from protobuf field <code>int32 digits = 2 [(.validate.rules) = {</code>
     * @return int
     */
    public function getDigits()
    {
        return $this->digits;
    }

    /**
     * Passcode digits length.
     *
     * Generated from protobuf field <code>int32 digits = 2 [(.validate.rules) = {</code>
     * @param int $var
     * @return $this
     */
    public function setDigits($var)
    {
        GPBUtil::checkInt32($var);
        $this->digits = $var;

        return $this;
    }

    /**
     * Hardware TOTP secret. Only included during identity creation. When used in JSON, the value will be represented as a base64 string.
     *
     * Generated from protobuf field <code>bytes secret = 3 [(.validate.rules) = {</code>
     * @return string
     */
    public function getSecret()
    {
        return $this->secret;
    }

    /**
     * Hardware TOTP secret. Only included during identity creation. When used in JSON, the value will be represented as a base64 string.
     *
     * Generated from protobuf field <code>bytes secret = 3 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setSecret($var)
    {
        GPBUtil::checkString($var, False);
        $this->secret = $var;

        return $this;
    }

}

