<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/ownmfa_app_identity.proto

namespace Ownmfa\Api;

use UnexpectedValueException;

/**
 * IdentityStatus represents the status of an identity.
 *
 * Protobuf type <code>ownmfa.api.IdentityStatus</code>
 */
class IdentityStatus
{
    /**
     * Identity is not yet verified.
     *
     * Generated from protobuf enum <code>UNVERIFIED = 0;</code>
     */
    const UNVERIFIED = 0;
    /**
     * Identity has been activated.
     *
     * Generated from protobuf enum <code>ACTIVATED = 3;</code>
     */
    const ACTIVATED = 3;

    private static $valueToName = [
        self::UNVERIFIED => 'UNVERIFIED',
        self::ACTIVATED => 'ACTIVATED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

