<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/ownmfa_org.proto

namespace Ownmfa\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ListOrgsResponse is sent in response to an organization list.
 *
 * Generated from protobuf message <code>ownmfa.api.ListOrgsResponse</code>
 */
class ListOrgsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Org array, ordered by ascending created_at timestamp.
     *
     * Generated from protobuf field <code>repeated .ownmfa.api.Org orgs = 1;</code>
     */
    private $orgs;
    /**
     * Pagination token used to retrieve the next page of results. Not returned for the last page.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';
    /**
     * Total number of organizations available.
     *
     * Generated from protobuf field <code>int32 total_size = 3;</code>
     */
    protected $total_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Ownmfa\Api\Org>|\Google\Protobuf\Internal\RepeatedField $orgs
     *           Org array, ordered by ascending created_at timestamp.
     *     @type string $next_page_token
     *           Pagination token used to retrieve the next page of results. Not returned for the last page.
     *     @type int $total_size
     *           Total number of organizations available.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\OwnmfaOrg::initOnce();
        parent::__construct($data);
    }

    /**
     * Org array, ordered by ascending created_at timestamp.
     *
     * Generated from protobuf field <code>repeated .ownmfa.api.Org orgs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrgs()
    {
        return $this->orgs;
    }

    /**
     * Org array, ordered by ascending created_at timestamp.
     *
     * Generated from protobuf field <code>repeated .ownmfa.api.Org orgs = 1;</code>
     * @param array<\Ownmfa\Api\Org>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ownmfa\Api\Org::class);
        $this->orgs = $arr;

        return $this;
    }

    /**
     * Pagination token used to retrieve the next page of results. Not returned for the last page.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Pagination token used to retrieve the next page of results. Not returned for the last page.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

    /**
     * Total number of organizations available.
     *
     * Generated from protobuf field <code>int32 total_size = 3;</code>
     * @return int
     */
    public function getTotalSize()
    {
        return $this->total_size;
    }

    /**
     * Total number of organizations available.
     *
     * Generated from protobuf field <code>int32 total_size = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_size = $var;

        return $this;
    }

}

