// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/ownmfa_event.proto
// Protobuf C++ Version: 5.29.4

#ifndef api_2fownmfa_5fevent_2eproto_2epb_2eh
#define api_2fownmfa_5fevent_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/timestamp.pb.h"
#include "google/api/annotations.pb.h"
#include "google/api/field_behavior.pb.h"
#include "validate/validate.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_api_2fownmfa_5fevent_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_api_2fownmfa_5fevent_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_api_2fownmfa_5fevent_2eproto;
namespace ownmfa {
namespace api {
class Event;
struct EventDefaultTypeInternal;
extern EventDefaultTypeInternal _Event_default_instance_;
class LatestEventsRequest;
struct LatestEventsRequestDefaultTypeInternal;
extern LatestEventsRequestDefaultTypeInternal _LatestEventsRequest_default_instance_;
class LatestEventsResponse;
struct LatestEventsResponseDefaultTypeInternal;
extern LatestEventsResponseDefaultTypeInternal _LatestEventsResponse_default_instance_;
class ListEventsRequest;
struct ListEventsRequestDefaultTypeInternal;
extern ListEventsRequestDefaultTypeInternal _ListEventsRequest_default_instance_;
class ListEventsResponse;
struct ListEventsResponseDefaultTypeInternal;
extern ListEventsResponseDefaultTypeInternal _ListEventsResponse_default_instance_;
}  // namespace api
}  // namespace ownmfa
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace ownmfa {
namespace api {
enum EventStatus : int {
  EVENT_STATUS_UNSPECIFIED = 0,
  IDENTITY_CREATED = 1,
  CHALLENGE_SENT = 2,
  CHALLENGE_NOOP = 3,
  CHALLENGE_FAIL = 4,
  ACTIVATE_SUCCESS = 5,
  ACTIVATE_FAIL = 6,
  VERIFY_SUCCESS = 7,
  VERIFY_FAIL = 8,
  IDENTITY_DELETED = 9,
  EventStatus_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  EventStatus_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool EventStatus_IsValid(int value);
extern const uint32_t EventStatus_internal_data_[];
constexpr EventStatus EventStatus_MIN = static_cast<EventStatus>(0);
constexpr EventStatus EventStatus_MAX = static_cast<EventStatus>(9);
constexpr int EventStatus_ARRAYSIZE = 9 + 1;
const ::google::protobuf::EnumDescriptor*
EventStatus_descriptor();
template <typename T>
const std::string& EventStatus_Name(T value) {
  static_assert(std::is_same<T, EventStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EventStatus_Name().");
  return EventStatus_Name(static_cast<EventStatus>(value));
}
template <>
inline const std::string& EventStatus_Name(EventStatus value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EventStatus_descriptor,
                                                 0, 9>(
      static_cast<int>(value));
}
inline bool EventStatus_Parse(absl::string_view name, EventStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EventStatus>(
      EventStatus_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class LatestEventsRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ownmfa.api.LatestEventsRequest) */ {
 public:
  inline LatestEventsRequest() : LatestEventsRequest(nullptr) {}
  ~LatestEventsRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LatestEventsRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LatestEventsRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LatestEventsRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline LatestEventsRequest(const LatestEventsRequest& from) : LatestEventsRequest(nullptr, from) {}
  inline LatestEventsRequest(LatestEventsRequest&& from) noexcept
      : LatestEventsRequest(nullptr, std::move(from)) {}
  inline LatestEventsRequest& operator=(const LatestEventsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LatestEventsRequest& operator=(LatestEventsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LatestEventsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const LatestEventsRequest* internal_default_instance() {
    return reinterpret_cast<const LatestEventsRequest*>(
        &_LatestEventsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(LatestEventsRequest& a, LatestEventsRequest& b) { a.Swap(&b); }
  inline void Swap(LatestEventsRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LatestEventsRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LatestEventsRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LatestEventsRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LatestEventsRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LatestEventsRequest& from) { LatestEventsRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LatestEventsRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ownmfa.api.LatestEventsRequest"; }

 protected:
  explicit LatestEventsRequest(::google::protobuf::Arena* arena);
  LatestEventsRequest(::google::protobuf::Arena* arena, const LatestEventsRequest& from);
  LatestEventsRequest(::google::protobuf::Arena* arena, LatestEventsRequest&& from) noexcept
      : LatestEventsRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAppIdFieldNumber = 1,
    kIdentityIdFieldNumber = 2,
  };
  // string app_id = 1 [json_name = "appID", (.validate.rules) = {
  void clear_app_id() ;
  const std::string& app_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_app_id(Arg_&& arg, Args_... args);
  std::string* mutable_app_id();
  PROTOBUF_NODISCARD std::string* release_app_id();
  void set_allocated_app_id(std::string* value);

  private:
  const std::string& _internal_app_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_app_id(
      const std::string& value);
  std::string* _internal_mutable_app_id();

  public:
  // string identity_id = 2 [json_name = "identityID", (.validate.rules) = {
  void clear_identity_id() ;
  const std::string& identity_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_identity_id(Arg_&& arg, Args_... args);
  std::string* mutable_identity_id();
  PROTOBUF_NODISCARD std::string* release_identity_id();
  void set_allocated_identity_id(std::string* value);

  private:
  const std::string& _internal_identity_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_identity_id(
      const std::string& value);
  std::string* _internal_mutable_identity_id();

  public:
  // @@protoc_insertion_point(class_scope:ownmfa.api.LatestEventsRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      56, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const LatestEventsRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr app_id_;
    ::google::protobuf::internal::ArenaStringPtr identity_id_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2fownmfa_5fevent_2eproto;
};
// -------------------------------------------------------------------

class ListEventsRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ownmfa.api.ListEventsRequest) */ {
 public:
  inline ListEventsRequest() : ListEventsRequest(nullptr) {}
  ~ListEventsRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ListEventsRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ListEventsRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ListEventsRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ListEventsRequest(const ListEventsRequest& from) : ListEventsRequest(nullptr, from) {}
  inline ListEventsRequest(ListEventsRequest&& from) noexcept
      : ListEventsRequest(nullptr, std::move(from)) {}
  inline ListEventsRequest& operator=(const ListEventsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListEventsRequest& operator=(ListEventsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListEventsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ListEventsRequest* internal_default_instance() {
    return reinterpret_cast<const ListEventsRequest*>(
        &_ListEventsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ListEventsRequest& a, ListEventsRequest& b) { a.Swap(&b); }
  inline void Swap(ListEventsRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListEventsRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListEventsRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ListEventsRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ListEventsRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ListEventsRequest& from) { ListEventsRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ListEventsRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ownmfa.api.ListEventsRequest"; }

 protected:
  explicit ListEventsRequest(::google::protobuf::Arena* arena);
  ListEventsRequest(::google::protobuf::Arena* arena, const ListEventsRequest& from);
  ListEventsRequest(::google::protobuf::Arena* arena, ListEventsRequest&& from) noexcept
      : ListEventsRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdentityIdFieldNumber = 1,
    kEndTimeFieldNumber = 2,
    kStartTimeFieldNumber = 3,
  };
  // string identity_id = 1 [json_name = "identityID", (.google.api.field_behavior) = REQUIRED, (.validate.rules) = {
  void clear_identity_id() ;
  const std::string& identity_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_identity_id(Arg_&& arg, Args_... args);
  std::string* mutable_identity_id();
  PROTOBUF_NODISCARD std::string* release_identity_id();
  void set_allocated_identity_id(std::string* value);

  private:
  const std::string& _internal_identity_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_identity_id(
      const std::string& value);
  std::string* _internal_mutable_identity_id();

  public:
  // .google.protobuf.Timestamp end_time = 2;
  bool has_end_time() const;
  void clear_end_time() ;
  const ::google::protobuf::Timestamp& end_time() const;
  PROTOBUF_NODISCARD ::google::protobuf::Timestamp* release_end_time();
  ::google::protobuf::Timestamp* mutable_end_time();
  void set_allocated_end_time(::google::protobuf::Timestamp* value);
  void unsafe_arena_set_allocated_end_time(::google::protobuf::Timestamp* value);
  ::google::protobuf::Timestamp* unsafe_arena_release_end_time();

  private:
  const ::google::protobuf::Timestamp& _internal_end_time() const;
  ::google::protobuf::Timestamp* _internal_mutable_end_time();

  public:
  // .google.protobuf.Timestamp start_time = 3;
  bool has_start_time() const;
  void clear_start_time() ;
  const ::google::protobuf::Timestamp& start_time() const;
  PROTOBUF_NODISCARD ::google::protobuf::Timestamp* release_start_time();
  ::google::protobuf::Timestamp* mutable_start_time();
  void set_allocated_start_time(::google::protobuf::Timestamp* value);
  void unsafe_arena_set_allocated_start_time(::google::protobuf::Timestamp* value);
  ::google::protobuf::Timestamp* unsafe_arena_release_start_time();

  private:
  const ::google::protobuf::Timestamp& _internal_start_time() const;
  ::google::protobuf::Timestamp* _internal_mutable_start_time();

  public:
  // @@protoc_insertion_point(class_scope:ownmfa.api.ListEventsRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 2,
      48, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ListEventsRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr identity_id_;
    ::google::protobuf::Timestamp* end_time_;
    ::google::protobuf::Timestamp* start_time_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2fownmfa_5fevent_2eproto;
};
// -------------------------------------------------------------------

class Event final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ownmfa.api.Event) */ {
 public:
  inline Event() : Event(nullptr) {}
  ~Event() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Event* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Event));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Event(
      ::google::protobuf::internal::ConstantInitialized);

  inline Event(const Event& from) : Event(nullptr, from) {}
  inline Event(Event&& from) noexcept
      : Event(nullptr, std::move(from)) {}
  inline Event& operator=(const Event& from) {
    CopyFrom(from);
    return *this;
  }
  inline Event& operator=(Event&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Event& default_instance() {
    return *internal_default_instance();
  }
  static inline const Event* internal_default_instance() {
    return reinterpret_cast<const Event*>(
        &_Event_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Event& a, Event& b) { a.Swap(&b); }
  inline void Swap(Event* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Event* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Event* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Event>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Event& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Event& from) { Event::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Event* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ownmfa.api.Event"; }

 protected:
  explicit Event(::google::protobuf::Arena* arena);
  Event(::google::protobuf::Arena* arena, const Event& from);
  Event(::google::protobuf::Arena* arena, Event&& from) noexcept
      : Event(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOrgIdFieldNumber = 1,
    kAppIdFieldNumber = 2,
    kIdentityIdFieldNumber = 3,
    kErrorFieldNumber = 5,
    kTraceIdFieldNumber = 7,
    kCreatedAtFieldNumber = 6,
    kStatusFieldNumber = 4,
  };
  // string org_id = 1 [json_name = "orgID"];
  void clear_org_id() ;
  const std::string& org_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_org_id(Arg_&& arg, Args_... args);
  std::string* mutable_org_id();
  PROTOBUF_NODISCARD std::string* release_org_id();
  void set_allocated_org_id(std::string* value);

  private:
  const std::string& _internal_org_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_org_id(
      const std::string& value);
  std::string* _internal_mutable_org_id();

  public:
  // string app_id = 2 [json_name = "appID"];
  void clear_app_id() ;
  const std::string& app_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_app_id(Arg_&& arg, Args_... args);
  std::string* mutable_app_id();
  PROTOBUF_NODISCARD std::string* release_app_id();
  void set_allocated_app_id(std::string* value);

  private:
  const std::string& _internal_app_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_app_id(
      const std::string& value);
  std::string* _internal_mutable_app_id();

  public:
  // string identity_id = 3 [json_name = "identityID"];
  void clear_identity_id() ;
  const std::string& identity_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_identity_id(Arg_&& arg, Args_... args);
  std::string* mutable_identity_id();
  PROTOBUF_NODISCARD std::string* release_identity_id();
  void set_allocated_identity_id(std::string* value);

  private:
  const std::string& _internal_identity_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_identity_id(
      const std::string& value);
  std::string* _internal_mutable_identity_id();

  public:
  // string error = 5;
  void clear_error() ;
  const std::string& error() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_error(Arg_&& arg, Args_... args);
  std::string* mutable_error();
  PROTOBUF_NODISCARD std::string* release_error();
  void set_allocated_error(std::string* value);

  private:
  const std::string& _internal_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error(
      const std::string& value);
  std::string* _internal_mutable_error();

  public:
  // string trace_id = 7;
  void clear_trace_id() ;
  const std::string& trace_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_trace_id(Arg_&& arg, Args_... args);
  std::string* mutable_trace_id();
  PROTOBUF_NODISCARD std::string* release_trace_id();
  void set_allocated_trace_id(std::string* value);

  private:
  const std::string& _internal_trace_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_trace_id(
      const std::string& value);
  std::string* _internal_mutable_trace_id();

  public:
  // .google.protobuf.Timestamp created_at = 6;
  bool has_created_at() const;
  void clear_created_at() ;
  const ::google::protobuf::Timestamp& created_at() const;
  PROTOBUF_NODISCARD ::google::protobuf::Timestamp* release_created_at();
  ::google::protobuf::Timestamp* mutable_created_at();
  void set_allocated_created_at(::google::protobuf::Timestamp* value);
  void unsafe_arena_set_allocated_created_at(::google::protobuf::Timestamp* value);
  ::google::protobuf::Timestamp* unsafe_arena_release_created_at();

  private:
  const ::google::protobuf::Timestamp& _internal_created_at() const;
  ::google::protobuf::Timestamp* _internal_mutable_created_at();

  public:
  // .ownmfa.api.EventStatus status = 4;
  void clear_status() ;
  ::ownmfa::api::EventStatus status() const;
  void set_status(::ownmfa::api::EventStatus value);

  private:
  ::ownmfa::api::EventStatus _internal_status() const;
  void _internal_set_status(::ownmfa::api::EventStatus value);

  public:
  // @@protoc_insertion_point(class_scope:ownmfa.api.Event)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 1,
      61, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Event& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr org_id_;
    ::google::protobuf::internal::ArenaStringPtr app_id_;
    ::google::protobuf::internal::ArenaStringPtr identity_id_;
    ::google::protobuf::internal::ArenaStringPtr error_;
    ::google::protobuf::internal::ArenaStringPtr trace_id_;
    ::google::protobuf::Timestamp* created_at_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2fownmfa_5fevent_2eproto;
};
// -------------------------------------------------------------------

class ListEventsResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ownmfa.api.ListEventsResponse) */ {
 public:
  inline ListEventsResponse() : ListEventsResponse(nullptr) {}
  ~ListEventsResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ListEventsResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ListEventsResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ListEventsResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline ListEventsResponse(const ListEventsResponse& from) : ListEventsResponse(nullptr, from) {}
  inline ListEventsResponse(ListEventsResponse&& from) noexcept
      : ListEventsResponse(nullptr, std::move(from)) {}
  inline ListEventsResponse& operator=(const ListEventsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListEventsResponse& operator=(ListEventsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListEventsResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ListEventsResponse* internal_default_instance() {
    return reinterpret_cast<const ListEventsResponse*>(
        &_ListEventsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ListEventsResponse& a, ListEventsResponse& b) { a.Swap(&b); }
  inline void Swap(ListEventsResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListEventsResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListEventsResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ListEventsResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ListEventsResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ListEventsResponse& from) { ListEventsResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ListEventsResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ownmfa.api.ListEventsResponse"; }

 protected:
  explicit ListEventsResponse(::google::protobuf::Arena* arena);
  ListEventsResponse(::google::protobuf::Arena* arena, const ListEventsResponse& from);
  ListEventsResponse(::google::protobuf::Arena* arena, ListEventsResponse&& from) noexcept
      : ListEventsResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEventsFieldNumber = 1,
  };
  // repeated .ownmfa.api.Event events = 1;
  int events_size() const;
  private:
  int _internal_events_size() const;

  public:
  void clear_events() ;
  ::ownmfa::api::Event* mutable_events(int index);
  ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>* mutable_events();

  private:
  const ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>& _internal_events() const;
  ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>* _internal_mutable_events();
  public:
  const ::ownmfa::api::Event& events(int index) const;
  ::ownmfa::api::Event* add_events();
  const ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>& events() const;
  // @@protoc_insertion_point(class_scope:ownmfa.api.ListEventsResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ListEventsResponse& from_msg);
    ::google::protobuf::RepeatedPtrField< ::ownmfa::api::Event > events_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2fownmfa_5fevent_2eproto;
};
// -------------------------------------------------------------------

class LatestEventsResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ownmfa.api.LatestEventsResponse) */ {
 public:
  inline LatestEventsResponse() : LatestEventsResponse(nullptr) {}
  ~LatestEventsResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LatestEventsResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LatestEventsResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LatestEventsResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline LatestEventsResponse(const LatestEventsResponse& from) : LatestEventsResponse(nullptr, from) {}
  inline LatestEventsResponse(LatestEventsResponse&& from) noexcept
      : LatestEventsResponse(nullptr, std::move(from)) {}
  inline LatestEventsResponse& operator=(const LatestEventsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline LatestEventsResponse& operator=(LatestEventsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LatestEventsResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const LatestEventsResponse* internal_default_instance() {
    return reinterpret_cast<const LatestEventsResponse*>(
        &_LatestEventsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(LatestEventsResponse& a, LatestEventsResponse& b) { a.Swap(&b); }
  inline void Swap(LatestEventsResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LatestEventsResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LatestEventsResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LatestEventsResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LatestEventsResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LatestEventsResponse& from) { LatestEventsResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LatestEventsResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ownmfa.api.LatestEventsResponse"; }

 protected:
  explicit LatestEventsResponse(::google::protobuf::Arena* arena);
  LatestEventsResponse(::google::protobuf::Arena* arena, const LatestEventsResponse& from);
  LatestEventsResponse(::google::protobuf::Arena* arena, LatestEventsResponse&& from) noexcept
      : LatestEventsResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEventsFieldNumber = 1,
  };
  // repeated .ownmfa.api.Event events = 1;
  int events_size() const;
  private:
  int _internal_events_size() const;

  public:
  void clear_events() ;
  ::ownmfa::api::Event* mutable_events(int index);
  ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>* mutable_events();

  private:
  const ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>& _internal_events() const;
  ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>* _internal_mutable_events();
  public:
  const ::ownmfa::api::Event& events(int index) const;
  ::ownmfa::api::Event* add_events();
  const ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>& events() const;
  // @@protoc_insertion_point(class_scope:ownmfa.api.LatestEventsResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const LatestEventsResponse& from_msg);
    ::google::protobuf::RepeatedPtrField< ::ownmfa::api::Event > events_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2fownmfa_5fevent_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Event

// string org_id = 1 [json_name = "orgID"];
inline void Event::clear_org_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.org_id_.ClearToEmpty();
}
inline const std::string& Event::org_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ownmfa.api.Event.org_id)
  return _internal_org_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Event::set_org_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.org_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ownmfa.api.Event.org_id)
}
inline std::string* Event::mutable_org_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_org_id();
  // @@protoc_insertion_point(field_mutable:ownmfa.api.Event.org_id)
  return _s;
}
inline const std::string& Event::_internal_org_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.org_id_.Get();
}
inline void Event::_internal_set_org_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.org_id_.Set(value, GetArena());
}
inline std::string* Event::_internal_mutable_org_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.org_id_.Mutable( GetArena());
}
inline std::string* Event::release_org_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ownmfa.api.Event.org_id)
  return _impl_.org_id_.Release();
}
inline void Event::set_allocated_org_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.org_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.org_id_.IsDefault()) {
    _impl_.org_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ownmfa.api.Event.org_id)
}

// string app_id = 2 [json_name = "appID"];
inline void Event::clear_app_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_id_.ClearToEmpty();
}
inline const std::string& Event::app_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ownmfa.api.Event.app_id)
  return _internal_app_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Event::set_app_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ownmfa.api.Event.app_id)
}
inline std::string* Event::mutable_app_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_app_id();
  // @@protoc_insertion_point(field_mutable:ownmfa.api.Event.app_id)
  return _s;
}
inline const std::string& Event::_internal_app_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.app_id_.Get();
}
inline void Event::_internal_set_app_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_id_.Set(value, GetArena());
}
inline std::string* Event::_internal_mutable_app_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.app_id_.Mutable( GetArena());
}
inline std::string* Event::release_app_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ownmfa.api.Event.app_id)
  return _impl_.app_id_.Release();
}
inline void Event::set_allocated_app_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.app_id_.IsDefault()) {
    _impl_.app_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ownmfa.api.Event.app_id)
}

// string identity_id = 3 [json_name = "identityID"];
inline void Event::clear_identity_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identity_id_.ClearToEmpty();
}
inline const std::string& Event::identity_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ownmfa.api.Event.identity_id)
  return _internal_identity_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Event::set_identity_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identity_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ownmfa.api.Event.identity_id)
}
inline std::string* Event::mutable_identity_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_identity_id();
  // @@protoc_insertion_point(field_mutable:ownmfa.api.Event.identity_id)
  return _s;
}
inline const std::string& Event::_internal_identity_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.identity_id_.Get();
}
inline void Event::_internal_set_identity_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identity_id_.Set(value, GetArena());
}
inline std::string* Event::_internal_mutable_identity_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.identity_id_.Mutable( GetArena());
}
inline std::string* Event::release_identity_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ownmfa.api.Event.identity_id)
  return _impl_.identity_id_.Release();
}
inline void Event::set_allocated_identity_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identity_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.identity_id_.IsDefault()) {
    _impl_.identity_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ownmfa.api.Event.identity_id)
}

// .ownmfa.api.EventStatus status = 4;
inline void Event::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
}
inline ::ownmfa::api::EventStatus Event::status() const {
  // @@protoc_insertion_point(field_get:ownmfa.api.Event.status)
  return _internal_status();
}
inline void Event::set_status(::ownmfa::api::EventStatus value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:ownmfa.api.Event.status)
}
inline ::ownmfa::api::EventStatus Event::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::ownmfa::api::EventStatus>(_impl_.status_);
}
inline void Event::_internal_set_status(::ownmfa::api::EventStatus value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// string error = 5;
inline void Event::clear_error() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_.ClearToEmpty();
}
inline const std::string& Event::error() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ownmfa.api.Event.error)
  return _internal_error();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Event::set_error(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ownmfa.api.Event.error)
}
inline std::string* Event::mutable_error() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:ownmfa.api.Event.error)
  return _s;
}
inline const std::string& Event::_internal_error() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_.Get();
}
inline void Event::_internal_set_error(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_.Set(value, GetArena());
}
inline std::string* Event::_internal_mutable_error() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.error_.Mutable( GetArena());
}
inline std::string* Event::release_error() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ownmfa.api.Event.error)
  return _impl_.error_.Release();
}
inline void Event::set_allocated_error(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.error_.IsDefault()) {
    _impl_.error_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ownmfa.api.Event.error)
}

// .google.protobuf.Timestamp created_at = 6;
inline bool Event::has_created_at() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.created_at_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& Event::_internal_created_at() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.created_at_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& Event::created_at() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ownmfa.api.Event.created_at)
  return _internal_created_at();
}
inline void Event::unsafe_arena_set_allocated_created_at(::google::protobuf::Timestamp* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.created_at_);
  }
  _impl_.created_at_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ownmfa.api.Event.created_at)
}
inline ::google::protobuf::Timestamp* Event::release_created_at() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* released = _impl_.created_at_;
  _impl_.created_at_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Timestamp* Event::unsafe_arena_release_created_at() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ownmfa.api.Event.created_at)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* temp = _impl_.created_at_;
  _impl_.created_at_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* Event::_internal_mutable_created_at() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.created_at_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.created_at_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.created_at_;
}
inline ::google::protobuf::Timestamp* Event::mutable_created_at() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::google::protobuf::Timestamp* _msg = _internal_mutable_created_at();
  // @@protoc_insertion_point(field_mutable:ownmfa.api.Event.created_at)
  return _msg;
}
inline void Event::set_allocated_created_at(::google::protobuf::Timestamp* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.created_at_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.created_at_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:ownmfa.api.Event.created_at)
}

// string trace_id = 7;
inline void Event::clear_trace_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trace_id_.ClearToEmpty();
}
inline const std::string& Event::trace_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ownmfa.api.Event.trace_id)
  return _internal_trace_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Event::set_trace_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trace_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ownmfa.api.Event.trace_id)
}
inline std::string* Event::mutable_trace_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_trace_id();
  // @@protoc_insertion_point(field_mutable:ownmfa.api.Event.trace_id)
  return _s;
}
inline const std::string& Event::_internal_trace_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.trace_id_.Get();
}
inline void Event::_internal_set_trace_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trace_id_.Set(value, GetArena());
}
inline std::string* Event::_internal_mutable_trace_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.trace_id_.Mutable( GetArena());
}
inline std::string* Event::release_trace_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ownmfa.api.Event.trace_id)
  return _impl_.trace_id_.Release();
}
inline void Event::set_allocated_trace_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trace_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.trace_id_.IsDefault()) {
    _impl_.trace_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ownmfa.api.Event.trace_id)
}

// -------------------------------------------------------------------

// ListEventsRequest

// string identity_id = 1 [json_name = "identityID", (.google.api.field_behavior) = REQUIRED, (.validate.rules) = {
inline void ListEventsRequest::clear_identity_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identity_id_.ClearToEmpty();
}
inline const std::string& ListEventsRequest::identity_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ownmfa.api.ListEventsRequest.identity_id)
  return _internal_identity_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ListEventsRequest::set_identity_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identity_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ownmfa.api.ListEventsRequest.identity_id)
}
inline std::string* ListEventsRequest::mutable_identity_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_identity_id();
  // @@protoc_insertion_point(field_mutable:ownmfa.api.ListEventsRequest.identity_id)
  return _s;
}
inline const std::string& ListEventsRequest::_internal_identity_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.identity_id_.Get();
}
inline void ListEventsRequest::_internal_set_identity_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identity_id_.Set(value, GetArena());
}
inline std::string* ListEventsRequest::_internal_mutable_identity_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.identity_id_.Mutable( GetArena());
}
inline std::string* ListEventsRequest::release_identity_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ownmfa.api.ListEventsRequest.identity_id)
  return _impl_.identity_id_.Release();
}
inline void ListEventsRequest::set_allocated_identity_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identity_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.identity_id_.IsDefault()) {
    _impl_.identity_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ownmfa.api.ListEventsRequest.identity_id)
}

// .google.protobuf.Timestamp end_time = 2;
inline bool ListEventsRequest::has_end_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.end_time_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& ListEventsRequest::_internal_end_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.end_time_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& ListEventsRequest::end_time() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ownmfa.api.ListEventsRequest.end_time)
  return _internal_end_time();
}
inline void ListEventsRequest::unsafe_arena_set_allocated_end_time(::google::protobuf::Timestamp* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.end_time_);
  }
  _impl_.end_time_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ownmfa.api.ListEventsRequest.end_time)
}
inline ::google::protobuf::Timestamp* ListEventsRequest::release_end_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* released = _impl_.end_time_;
  _impl_.end_time_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Timestamp* ListEventsRequest::unsafe_arena_release_end_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ownmfa.api.ListEventsRequest.end_time)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* temp = _impl_.end_time_;
  _impl_.end_time_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* ListEventsRequest::_internal_mutable_end_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.end_time_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.end_time_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.end_time_;
}
inline ::google::protobuf::Timestamp* ListEventsRequest::mutable_end_time() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::google::protobuf::Timestamp* _msg = _internal_mutable_end_time();
  // @@protoc_insertion_point(field_mutable:ownmfa.api.ListEventsRequest.end_time)
  return _msg;
}
inline void ListEventsRequest::set_allocated_end_time(::google::protobuf::Timestamp* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.end_time_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.end_time_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:ownmfa.api.ListEventsRequest.end_time)
}

// .google.protobuf.Timestamp start_time = 3;
inline bool ListEventsRequest::has_start_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.start_time_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& ListEventsRequest::_internal_start_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.start_time_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& ListEventsRequest::start_time() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ownmfa.api.ListEventsRequest.start_time)
  return _internal_start_time();
}
inline void ListEventsRequest::unsafe_arena_set_allocated_start_time(::google::protobuf::Timestamp* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.start_time_);
  }
  _impl_.start_time_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ownmfa.api.ListEventsRequest.start_time)
}
inline ::google::protobuf::Timestamp* ListEventsRequest::release_start_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::google::protobuf::Timestamp* released = _impl_.start_time_;
  _impl_.start_time_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Timestamp* ListEventsRequest::unsafe_arena_release_start_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ownmfa.api.ListEventsRequest.start_time)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::google::protobuf::Timestamp* temp = _impl_.start_time_;
  _impl_.start_time_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* ListEventsRequest::_internal_mutable_start_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.start_time_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.start_time_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.start_time_;
}
inline ::google::protobuf::Timestamp* ListEventsRequest::mutable_start_time() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::google::protobuf::Timestamp* _msg = _internal_mutable_start_time();
  // @@protoc_insertion_point(field_mutable:ownmfa.api.ListEventsRequest.start_time)
  return _msg;
}
inline void ListEventsRequest::set_allocated_start_time(::google::protobuf::Timestamp* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.start_time_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.start_time_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:ownmfa.api.ListEventsRequest.start_time)
}

// -------------------------------------------------------------------

// ListEventsResponse

// repeated .ownmfa.api.Event events = 1;
inline int ListEventsResponse::_internal_events_size() const {
  return _internal_events().size();
}
inline int ListEventsResponse::events_size() const {
  return _internal_events_size();
}
inline void ListEventsResponse::clear_events() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.events_.Clear();
}
inline ::ownmfa::api::Event* ListEventsResponse::mutable_events(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ownmfa.api.ListEventsResponse.events)
  return _internal_mutable_events()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>* ListEventsResponse::mutable_events()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ownmfa.api.ListEventsResponse.events)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_events();
}
inline const ::ownmfa::api::Event& ListEventsResponse::events(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ownmfa.api.ListEventsResponse.events)
  return _internal_events().Get(index);
}
inline ::ownmfa::api::Event* ListEventsResponse::add_events() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::ownmfa::api::Event* _add = _internal_mutable_events()->Add();
  // @@protoc_insertion_point(field_add:ownmfa.api.ListEventsResponse.events)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>& ListEventsResponse::events() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ownmfa.api.ListEventsResponse.events)
  return _internal_events();
}
inline const ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>&
ListEventsResponse::_internal_events() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.events_;
}
inline ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>*
ListEventsResponse::_internal_mutable_events() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.events_;
}

// -------------------------------------------------------------------

// LatestEventsRequest

// string app_id = 1 [json_name = "appID", (.validate.rules) = {
inline void LatestEventsRequest::clear_app_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_id_.ClearToEmpty();
}
inline const std::string& LatestEventsRequest::app_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ownmfa.api.LatestEventsRequest.app_id)
  return _internal_app_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void LatestEventsRequest::set_app_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ownmfa.api.LatestEventsRequest.app_id)
}
inline std::string* LatestEventsRequest::mutable_app_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_app_id();
  // @@protoc_insertion_point(field_mutable:ownmfa.api.LatestEventsRequest.app_id)
  return _s;
}
inline const std::string& LatestEventsRequest::_internal_app_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.app_id_.Get();
}
inline void LatestEventsRequest::_internal_set_app_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_id_.Set(value, GetArena());
}
inline std::string* LatestEventsRequest::_internal_mutable_app_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.app_id_.Mutable( GetArena());
}
inline std::string* LatestEventsRequest::release_app_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ownmfa.api.LatestEventsRequest.app_id)
  return _impl_.app_id_.Release();
}
inline void LatestEventsRequest::set_allocated_app_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.app_id_.IsDefault()) {
    _impl_.app_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ownmfa.api.LatestEventsRequest.app_id)
}

// string identity_id = 2 [json_name = "identityID", (.validate.rules) = {
inline void LatestEventsRequest::clear_identity_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identity_id_.ClearToEmpty();
}
inline const std::string& LatestEventsRequest::identity_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ownmfa.api.LatestEventsRequest.identity_id)
  return _internal_identity_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void LatestEventsRequest::set_identity_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identity_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ownmfa.api.LatestEventsRequest.identity_id)
}
inline std::string* LatestEventsRequest::mutable_identity_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_identity_id();
  // @@protoc_insertion_point(field_mutable:ownmfa.api.LatestEventsRequest.identity_id)
  return _s;
}
inline const std::string& LatestEventsRequest::_internal_identity_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.identity_id_.Get();
}
inline void LatestEventsRequest::_internal_set_identity_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identity_id_.Set(value, GetArena());
}
inline std::string* LatestEventsRequest::_internal_mutable_identity_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.identity_id_.Mutable( GetArena());
}
inline std::string* LatestEventsRequest::release_identity_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ownmfa.api.LatestEventsRequest.identity_id)
  return _impl_.identity_id_.Release();
}
inline void LatestEventsRequest::set_allocated_identity_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identity_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.identity_id_.IsDefault()) {
    _impl_.identity_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ownmfa.api.LatestEventsRequest.identity_id)
}

// -------------------------------------------------------------------

// LatestEventsResponse

// repeated .ownmfa.api.Event events = 1;
inline int LatestEventsResponse::_internal_events_size() const {
  return _internal_events().size();
}
inline int LatestEventsResponse::events_size() const {
  return _internal_events_size();
}
inline void LatestEventsResponse::clear_events() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.events_.Clear();
}
inline ::ownmfa::api::Event* LatestEventsResponse::mutable_events(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ownmfa.api.LatestEventsResponse.events)
  return _internal_mutable_events()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>* LatestEventsResponse::mutable_events()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ownmfa.api.LatestEventsResponse.events)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_events();
}
inline const ::ownmfa::api::Event& LatestEventsResponse::events(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ownmfa.api.LatestEventsResponse.events)
  return _internal_events().Get(index);
}
inline ::ownmfa::api::Event* LatestEventsResponse::add_events() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::ownmfa::api::Event* _add = _internal_mutable_events()->Add();
  // @@protoc_insertion_point(field_add:ownmfa.api.LatestEventsResponse.events)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>& LatestEventsResponse::events() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ownmfa.api.LatestEventsResponse.events)
  return _internal_events();
}
inline const ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>&
LatestEventsResponse::_internal_events() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.events_;
}
inline ::google::protobuf::RepeatedPtrField<::ownmfa::api::Event>*
LatestEventsResponse::_internal_mutable_events() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.events_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace ownmfa


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ownmfa::api::EventStatus> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::ownmfa::api::EventStatus>() {
  return ::ownmfa::api::EventStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // api_2fownmfa_5fevent_2eproto_2epb_2eh
