// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/ownmfa_role.proto
// Protobuf C++ Version: 6.31.1

#include "api/ownmfa_role.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ownmfa {
namespace api {
}  // namespace api
}  // namespace ownmfa
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_api_2fownmfa_5frole_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_api_2fownmfa_5frole_2eproto = nullptr;
const ::uint32_t TableStruct_api_2fownmfa_5frole_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pb::Message* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_default_instances = nullptr;
const char descriptor_table_protodef_api_2fownmfa_5frole_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025api/ownmfa_role.proto\022\nownmfa.api*U\n\004R"
    "ole\022\024\n\020ROLE_UNSPECIFIED\020\000\022\n\n\006VIEWER\020\004\022\021\n"
    "\rAUTHENTICATOR\020\010\022\t\n\005ADMIN\020\014\022\r\n\tSYS_ADMIN"
    "\020\017B Z\036github.com/ownmfa/proto/go/apib\006pr"
    "oto3"
};
static ::absl::once_flag descriptor_table_api_2fownmfa_5frole_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_api_2fownmfa_5frole_2eproto = {
    false,
    false,
    164,
    descriptor_table_protodef_api_2fownmfa_5frole_2eproto,
    "api/ownmfa_role.proto",
    &descriptor_table_api_2fownmfa_5frole_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_api_2fownmfa_5frole_2eproto::offsets,
    file_level_enum_descriptors_api_2fownmfa_5frole_2eproto,
    file_level_service_descriptors_api_2fownmfa_5frole_2eproto,
};
namespace ownmfa {
namespace api {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Role_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_api_2fownmfa_5frole_2eproto);
  return file_level_enum_descriptors_api_2fownmfa_5frole_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Role_internal_data_[] = {
    65536u, 32u, 18568u, };
// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace ownmfa
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_api_2fownmfa_5frole_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
