FROM golang:1-alpine

RUN apk update && apk upgrade
RUN apk add --no-cache git make protobuf-dev
RUN git clone --depth=1 https://github.com/googleapis/googleapis.git \
/tmp/googleapis
RUN git clone --depth=1 https://github.com/grpc-ecosystem/grpc-gateway.git \
/tmp/grpc-gateway
RUN git clone --depth=1 https://github.com/bufbuild/protoc-gen-validate.git \
/tmp/pgv

WORKDIR /api
