# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api/ownmfa_org.proto for package 'ownmfa.api'

require 'grpc'
require 'api/ownmfa_org_pb'

module Ownmfa
  module Api
    module OrgService
      # OrgService contains functions to query and modify organizations.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'ownmfa.api.OrgService'

        # Create an organization. An organization is the top level resource and contains users, applications, and derived resources.
        rpc :CreateOrg, ::Ownmfa::Api::CreateOrgRequest, ::Ownmfa::Api::Org
        # Get an organization by ID. An organization is the top level resource and contains users, applications, and derived resources.
        rpc :GetOrg, ::Ownmfa::Api::GetOrgRequest, ::Ownmfa::Api::Org
        # Update an organization. An organization is the top level resource and contains users, applications, and derived resources.
        rpc :UpdateOrg, ::Ownmfa::Api::UpdateOrgRequest, ::Ownmfa::Api::Org
        # Delete an organization by ID. An organization is the top level resource and contains users, applications, and derived resources.
        rpc :DeleteOrg, ::Ownmfa::Api::DeleteOrgRequest, ::Google::Protobuf::Empty
        # List all organizations. An organization is the top level resource and contains users, applications, and derived resources.
        rpc :ListOrgs, ::Ownmfa::Api::ListOrgsRequest, ::Ownmfa::Api::ListOrgsResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
