# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api/session.proto for package 'ownmfa.api'

require 'grpc'
require 'api/session_pb'

module Ownmfa
  module Api
    module SessionService
      # SessionService contains functions to create sessions and keys.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'ownmfa.api.SessionService'

        # Log in a user. Login tokens are time-limited and accompanied by an expiration.
        rpc :Login, ::Ownmfa::Api::LoginRequest, ::Ownmfa::Api::LoginResponse
        # Create an API key. API keys are persistent and do not expire until revoked.
        rpc :CreateKey, ::Ownmfa::Api::CreateKeyRequest, ::Ownmfa::Api::CreateKeyResponse
        # Delete an API key by ID. API keys are persistent and do not expire until revoked.
        rpc :DeleteKey, ::Ownmfa::Api::DeleteKeyRequest, ::Google::Protobuf::Empty
        # List all API keys. API keys are persistent and do not expire until revoked.
        rpc :ListKeys, ::Ownmfa::Api::ListKeysRequest, ::Ownmfa::Api::ListKeysResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
